//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntControl.WebUI.SmevService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IncomingQueueStatsRequest", Namespace="urn://x-artefacts-electron-it-ru")]
    [System.SerializableAttribute()]
    public partial class IncomingQueueStatsRequest : Ohotnik.Smev.Client.SmevRouter.SmevSimpleRequestData {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryDirectionMode", Namespace="urn://x-artefacts-electron-it-ru")]
    public enum QueryDirectionMode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TestArea = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DevelopmentArea = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProductionArea = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IncomingQueueStatsResponse", Namespace="urn://x-artefacts-electron-it-ru")]
    [System.SerializableAttribute()]
    public partial class IncomingQueueStatsResponse : Ohotnik.Smev.Client.SmevRouter.SmevResponseData {
        
        private long PendingRequestCountField;
        
        private long PendingResponseCountField;
        
        private long PendingStatusCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long PendingRequestCount {
            get {
                return this.PendingRequestCountField;
            }
            set {
                this.PendingRequestCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long PendingResponseCount {
            get {
                return this.PendingResponseCountField;
            }
            set {
                this.PendingResponseCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long PendingStatusCount {
            get {
                return this.PendingStatusCountField;
            }
            set {
                this.PendingStatusCountField = value;
            }
        }
    }
}
